baseURL = "https://svampinfo.se/"
languageCode = "sv-se"
title = "Svampinfo"
theme = "PaperMod"
enableRobotsTXT = true

[params]
description = "Din guide till Sveriges svampar - mer än 150 arter med bilder och beskrivningar"
author = "Svampinfo"
keywords = [
  "svamp",
  "svampar",
  "matsvamp",
  "giftsvamp",
  "svampplockning",
  "sverige",
  "svampguiden",
  "artfakta",
  "nyckla",
  "hjälp",
  "guide",
]
disableThemeToggle = true
images = [ "/icons/favico.svg" ]

  [params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/icons/favicon-16x16.png"
  favicon32x32 = "/icons/favicon-32x32.png"
  apple_touch_icon = "/icons/apple-touch-icon.png"
  safari_pinned_tab = "/icons/favico.svg"
  theme_color = "#587570"

  [params.label]
  text = "Svampinfo"
  icon = "/icons/favico.svg"
  iconHeight = 30
  background_color_class = "bg-near-black"
  custom_css = [ "css/custom.css" ]

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
section = [ "HTML", "RSS" ]

[[menu.main]]
name = "Hem"
url = "/"
weight = 1

[[menu.main]]
name = "Alla svampar"
url = "/svampar/"
weight = 2

[[menu.main]]
name = "ADBVO"
url = "/allt-du-behöver-veta-om/"
weight = 3

[[menu.main]]
name = "Sök"
url = "/search/"
weight = 4
